apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: harbor.yyy/test/spring:getip
        ports:
        - containerPort: 9966 
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "1"
      imagePullSecrets:
        - name: harbor
